### ISSUE TITLE
strange training data

### ISSUE THREAD

**Issue by jackxpeng** [sheng-z/figet#2]
In train.txt I see a lot of annotations that don't make any sense to me.
For example
`0   1   Oh , after I shave it I rub on a little oil .   /person/athlete /person`
So the mention "Oh" is supposed to be categorized as an athlete???
`0   1   Do you wear a hat ? /other /other/religion`
Here "Do" is a religion?

**Comment by sheng-z** [comment]
The dataset is not created by me, and I agree it's not 100% clean.

**Comment by jackxpeng** [comment]
Got it. Thank you.

**Comment by jackxpeng** [comment]
Can you tell me where you downloaded the training data? Thank you.

**Comment by sheng-z** [comment]
You can find it in the [README](https://github.com/sheng-z/figet#acknowledgements).
